libbf: bf::stable_bloom_filter Class Reference
bf::stable_bloom_filter Class Reference
A stable Bloom filter.
#include <stable.h>
Public Member Functions
stable_bloom_filter (hasher h, size_t cells, size_t width, size_t d)
Constructs a stable Bloom filter.
virtual void add (object const &o) override
Adds an item to the stable Bloom filter.
Public Member Functions inherited from bf::counting_bloom_filter
counting_bloom_filter (hasher h, size_t cells, size_t width)
Constructs a counting Bloom filter.
counting_bloom_filter (counting_bloom_filter &&)=default
Move-constructs a counting Bloom filter.
virtual size_t lookup (object const &o) const override
Retrieves the count of an element.
virtual void clear () override
Removes all items from the Bloom filter.
void remove (object const &o)
Removes an element.
template<typename T >
void remove (T const &x)
Public Member Functions inherited from bf::bloom_filter
template<typename T >
void add (T const &x)
Adds an element to the Bloom filter.
template<typename T >
size_t lookup (T const &x) const
Retrieves the count of an element.
Private Attributes
size_t d_
std::mt19937 generator_
std::uniform_int_distribution unif_
Additional Inherited Members
Protected Member Functions inherited from bf::counting_bloom_filter
std::vector< size_t > find_indices (object const &o, bool part=false) const
Maps an object to the indices in the underlying counter vector.
size_t find_minimum (std::vector< size_t > const &indices) const
Finds the minimum value in a list of arbitrary indices.
std::vector< size_t > find_minima (std::vector< size_t > const &indices) const
Finds one or more minimum indices for a list of arbitrary indices.
bool increment (std::vector< size_t > const &indices, size_t value=1)
Increments a given set of indices in the underlying counter vector.
bool decrement (std::vector< size_t > const &indices, size_t value=1)
Decrements a given set of indices in the underlying counter vector.
size_t count (size_t index) const
Retrieves the counter for given cell index.
Protected Attributes inherited from bf::counting_bloom_filter
hasher hasher_
counter_vector cells_
Detailed Description
A stable Bloom filter.
Definition at line 10 of file stable.h.
Constructor & Destructor Documentation
bf::stable_bloom_filter::stable_bloom_filter (hasher h, size_t cells, size_t width, size_t d)
Constructs a stable Bloom filter.
Parameters
h The hasher.
cells The number of cells.
width The number of bits per cell.
d The number of cells to decrement before adding an element.
Precondition
cells <= d
Definition at line 7 of file stable.cc.
Member Function Documentation
void bf::stable_bloom_filter::add (object const & o) override virtual
Adds an item to the stable Bloom filter.
This invovles first decrementing k positions uniformly at random and then setting the counter of o to all 1s.
Parameters
o The object to add.
Reimplemented from bf::counting_bloom_filter.
Definition at line 16 of file stable.cc.
References bf::counter_vector::decrement(), bf::counting_bloom_filter::find_indices(), bf::counting_bloom_filter::increment(), and bf::counter_vector::max().
The documentation for this class was generated from the following files:
stable.h
stable.cc