libbf: bf::bitwise_bloom_filter Class Reference
bf::bitwise_bloom_filter Class Reference
The bitwise Bloom filter.
#include <bitwise.h>
Public Member Functions
bitwise_bloom_filter (size_t k, size_t cells, size_t seed=0)
Constructs a bitwise Bloom filter.
virtual void add (object const &o) override
Adds an element to the Bloom filter.
virtual size_t lookup (object const &o) const override
Retrieves the count of an element.
virtual void clear () override
Removes all items from the Bloom filter.
Public Member Functions inherited from bf::bloom_filter
template<typename T >
void add (T const &x)
Adds an element to the Bloom filter.
template<typename T >
size_t lookup (T const &x) const
Retrieves the count of an element.
Private Member Functions
void grow ()
Appends a new level.
Private Attributes
size_t k_
size_t cells_
size_t seed_
std::vector< basic_bloom_filter > levels_
Detailed Description
The bitwise Bloom filter.
Definition at line 9 of file bitwise.h.
Constructor & Destructor Documentation
bf::bitwise_bloom_filter::bitwise_bloom_filter (size_t k, size_t cells, size_t seed = 0)
Constructs a bitwise Bloom filter.
Parameters
k The number of hash functions in the first level.
cells0 The number of cells in the the first level.
seed0 The seed for the first level.
Definition at line 5 of file bitwise.cc.
References grow().
Member Function Documentation
void bf::bitwise_bloom_filter::add (object const & o) override virtual
Adds an element to the Bloom filter.
Parameters
o A wrapped object.
Implements bf::bloom_filter.
Definition at line 11 of file bitwise.cc.
References grow(), and lookup().
void bf::bitwise_bloom_filter::grow () private
Appends a new level.
Postcondition
levels_.size() += 1
Definition at line 44 of file bitwise.cc.
Referenced by add(), bitwise_bloom_filter(), and clear().
size_t bf::bitwise_bloom_filter::lookup (object const & o) const override virtual
Retrieves the count of an element.
Parameters
o A wrapped object.
Returns
A frequency estimate for o.
Implements bf::bloom_filter.
Definition at line 30 of file bitwise.cc.
Referenced by add().
The documentation for this class was generated from the following files:
bitwise.h
bitwise.cc