libbf: bf::counting_bloom_filter Class Reference
bf::counting_bloom_filter Class Reference
The counting Bloom filter.
#include <counting.h>
Public Member Functions
counting_bloom_filter (hasher h, size_t cells, size_t width)
Constructs a counting Bloom filter.
counting_bloom_filter (counting_bloom_filter &&)=default
Move-constructs a counting Bloom filter.
virtual void add (object const &o) override
Adds an element to the Bloom filter.
virtual size_t lookup (object const &o) const override
Retrieves the count of an element.
virtual void clear () override
Removes all items from the Bloom filter.
void remove (object const &o)
Removes an element.
template<typename T >
void remove (T const &x)
Public Member Functions inherited from bf::bloom_filter
template<typename T >
void add (T const &x)
Adds an element to the Bloom filter.
template<typename T >
size_t lookup (T const &x) const
Retrieves the count of an element.
Protected Member Functions
std::vector< size_t > find_indices (object const &o, bool part=false) const
Maps an object to the indices in the underlying counter vector.
size_t find_minimum (std::vector< size_t > const &indices) const
Finds the minimum value in a list of arbitrary indices.
std::vector< size_t > find_minima (std::vector< size_t > const &indices) const
Finds one or more minimum indices for a list of arbitrary indices.
bool increment (std::vector< size_t > const &indices, size_t value=1)
Increments a given set of indices in the underlying counter vector.
bool decrement (std::vector< size_t > const &indices, size_t value=1)
Decrements a given set of indices in the underlying counter vector.
size_t count (size_t index) const
Retrieves the counter for given cell index.
Protected Attributes
hasher hasher_
counter_vector cells_
Private Attributes
friend spectral_mi_bloom_filter
friend spectral_rm_bloom_filter
Detailed Description
The counting Bloom filter.
Definition at line 14 of file counting.h.
Constructor & Destructor Documentation
bf::counting_bloom_filter::counting_bloom_filter (hasher h, size_t cells, size_t width)
Constructs a counting Bloom filter.
Parameters
h The hasher.
cells The number of cells.
width The number of bits per cell.
Definition at line 8 of file counting.cc.
Member Function Documentation
void bf::counting_bloom_filter::add (object const & o) override virtual
Adds an element to the Bloom filter.
Parameters
o A wrapped object.
Implements bf::bloom_filter.
Reimplemented in bf::spectral_mi_bloom_filter, and bf::stable_bloom_filter.
Definition at line 15 of file counting.cc.
References find_indices(), and increment().
size_t bf::counting_bloom_filter::count (size_t index) const protected
Retrieves the counter for given cell index.
Parameters
index The index of the counter vector.
Precondition
index < cells.size()
Definition at line 119 of file counting.cc.
References bf::counter_vector::count().
Referenced by bf::spectral_rm_bloom_filter::add(), and bf::spectral_rm_bloom_filter::lookup().
bool bf::counting_bloom_filter::decrement (std::vector< size_t > const & indices, size_t value = 1) protected
Decrements a given set of indices in the underlying counter vector.
Parameters
indices The indices to decrement.
Returns
true iff no counter underflowed.
Definition at line 109 of file counting.cc.
References bf::counter_vector::decrement().
Referenced by remove(), and bf::spectral_rm_bloom_filter::remove().
std::vector< size_t > bf::counting_bloom_filter::find_indices (object const & o, bool part = false) const protected
Maps an object to the indices in the underlying counter vector.
Parameters
o The object to map.
part If false, the function maps o uniformly into the counter vector modding each digest with the number of available cells. If true, the function partitions the counter vector into k distinct sub-vectors and mods each digest into one sub-vector.
Returns
The indices corresponding to the digests of o.
Definition at line 43 of file counting.cc.
References bf::counter_vector::size().
Referenced by bf::stable_bloom_filter::add(), add(), bf::spectral_mi_bloom_filter::add(), bf::spectral_rm_bloom_filter::add(), lookup(), bf::spectral_rm_bloom_filter::lookup(), remove(), and bf::spectral_rm_bloom_filter::remove().
std::vector< size_t > bf::counting_bloom_filter::find_minima (std::vector< size_t > const & indices) const protected
Finds one or more minimum indices for a list of arbitrary indices.
Parameters
indices The indices over which to compute the minimum.
Returns
The indices corresponding to the minima in the counter vector.
Definition at line 78 of file counting.cc.
References bf::counter_vector::count(), and bf::counter_vector::max().
Referenced by bf::spectral_mi_bloom_filter::add(), bf::spectral_rm_bloom_filter::add(), bf::spectral_rm_bloom_filter::lookup(), and bf::spectral_rm_bloom_filter::remove().
size_t bf::counting_bloom_filter::find_minimum (std::vector< size_t > const & indices) const protected
Finds the minimum value in a list of arbitrary indices.
Parameters
indices The indices over which to compute the minimum.
Returns
The minimum counter value over indices.
Definition at line 65 of file counting.cc.
References bf::counter_vector::count(), and bf::counter_vector::max().
Referenced by bf::spectral_rm_bloom_filter::add(), bf::spectral_rm_bloom_filter::lookup(), and bf::spectral_rm_bloom_filter::remove().
bool bf::counting_bloom_filter::increment (std::vector< size_t > const & indices, size_t value = 1) protected
Increments a given set of indices in the underlying counter vector.
Parameters
indices The indices to increment.
Returns
true iff no counter overflowed.
Definition at line 99 of file counting.cc.
References bf::counter_vector::increment().
Referenced by bf::stable_bloom_filter::add(), add(), bf::spectral_mi_bloom_filter::add(), and bf::spectral_rm_bloom_filter::add().
size_t bf::counting_bloom_filter::lookup (object const & o) const override virtual
Retrieves the count of an element.
Parameters
o A wrapped object.
Returns
A frequency estimate for o.
Implements bf::bloom_filter.
Definition at line 20 of file counting.cc.
References bf::counter_vector::count(), find_indices(), and bf::counter_vector::max().
void bf::counting_bloom_filter::remove (object const & o)
Removes an element.
Parameters
o The object whose cells to decrement by 1.
Definition at line 37 of file counting.cc.
References decrement(), and find_indices().
The documentation for this class was generated from the following files:
counting.h
counting.cc