libbf: bf::spectral_rm_bloom_filter Class Reference
bf::spectral_rm_bloom_filter Class Reference
A spectral Bloom filter with recurring minimum (RM) policy.
#include <counting.h>
Public Member Functions
spectral_rm_bloom_filter (hasher h1, size_t cells1, size_t width1, hasher h2, size_t cells2, size_t width2)
Constructs a spectral RM Bloom filter.
virtual void add (object const &o) override
Adds an element to the Bloom filter.
virtual size_t lookup (object const &o) const override
Retrieves the count of an element.
virtual void clear () override
Removes all items from the Bloom filter.
void remove (object const &o)
Removes an element.
Public Member Functions inherited from bf::bloom_filter
template<typename T >
void add (T const &x)
Adds an element to the Bloom filter.
template<typename T >
size_t lookup (T const &x) const
Retrieves the count of an element.
Private Attributes
counting_bloom_filter first_
counting_bloom_filter second_
Detailed Description
A spectral Bloom filter with recurring minimum (RM) policy.
Definition at line 105 of file counting.h.
Constructor & Destructor Documentation
bf::spectral_rm_bloom_filter::spectral_rm_bloom_filter (hasher h1, size_t cells1, size_t width1, hasher h2, size_t cells2, size_t width2)
Constructs a spectral RM Bloom filter.
Parameters
h1 The first hasher.
cells1 The number of cells in the first Bloom filter.
width1 The number of bits per cell in the first Bloom filter.
h2 The second hasher.
cells2 The number of cells in the second Bloom filter.
width2 The number of bits per cell in the second Bloom filter.
Definition at line 136 of file counting.cc.
Member Function Documentation
void bf::spectral_rm_bloom_filter::add (object const & o) override virtual
Adds an element to the Bloom filter.
Parameters
o A wrapped object.
Implements bf::bloom_filter.
Definition at line 149 of file counting.cc.
References bf::counting_bloom_filter::count(), bf::counting_bloom_filter::find_indices(), bf::counting_bloom_filter::find_minima(), bf::counting_bloom_filter::find_minimum(), and bf::counting_bloom_filter::increment().
size_t bf::spectral_rm_bloom_filter::lookup (object const & o) const override virtual
Retrieves the count of an element.
Parameters
o A wrapped object.
Returns
A frequency estimate for o.
Implements bf::bloom_filter.
Definition at line 171 of file counting.cc.
References bf::counting_bloom_filter::count(), bf::counting_bloom_filter::find_indices(), bf::counting_bloom_filter::find_minima(), and bf::counting_bloom_filter::find_minimum().
void bf::spectral_rm_bloom_filter::remove (object const & o)
Removes an element.
Parameters
o The object whose cells to decrement by 1.
Definition at line 190 of file counting.cc.
References bf::counting_bloom_filter::decrement(), bf::counting_bloom_filter::find_indices(), bf::counting_bloom_filter::find_minima(), and bf::counting_bloom_filter::find_minimum().
The documentation for this class was generated from the following files:
counting.h
counting.cc